namespace BDSM
{
    public enum VariableType { BYTE }
    public enum ArgumentType { LITERAL, INPUT, OUTPUT, ADDRESS, LABEL, VARIABLE };
    public enum Inputs { NONE, REGISTER_A, REGISTER_B, LCD, PROG_COUNTER_H, PROG_COUNTER_L, INSTRUCTION, ARGUMENT, RAM_PAGE, RAM_ADDRESS, RAM, STACK, UNUSED_1, UNUSED_2, UNUSED_3 }
    public enum Outputs { NONE, REGISTER_A, REGISTER_B, ALU, PROG_COUNTER_H, PROG_COUNTER_L, PROGRAM_MEMORY, ARGUMENT, UNUSED_1, UNUSED_2, RAM, STACK, UNUSED_3, UNUSED_4, UNUSED_5 }

    public enum OpCodes
    {
        NOOP, HALT, RSET, MOVE_IO,
        MOVE_I_LIT, MOVE_I_VAR, MOVE_VAR_OUT, MOVE_VAR_LIT,
        POKE_FULL_LIT, POKE_FULL_OUT, ZPOKE_LIT, ZPOKE_OUT,
        PEEK_FULL, ZPEEK, DATA_FILLER1, DATA_FILLER2,

        MATH_LIT, MATH_ADD, MATH_LA, MATH_AL,
        ADD, ADDC, INC, SUB,
        SUBB, DEC, SHFL, ROTL,
        ARIT_FILLER1, ARIT_FILLER2, ARIT_FILLER3, ARIT_FILLER4,

        NOTA, NOR, ANNA, FALS,
        NAND, NOTB, XOR, ANNB,
        ORNA, XNOR, BOUT, AND,
        TRUE, ORNB, OR, AOUT,

        PUSH_OUT, PUSH_LIT, PUSH_VAR, POP_INP,
        POP_VAR, SWAP, STSH, RSTR,
        NPSH, NPOP, CALL, RTRN,
        STAK_FILLER1, STAK_FILLER2, STAK_FILLER3, STAK_FILLER4,

        JUMP, JMPC, JPNC, JMPZ,
        JPNZ, JMPE, JPNE, JMPG,
        JPNG, JMPL, JPNL, JUMP_FILLER1,
        JUMP_FILLER2, JUMP_FILLER3, JUMP_FILLER4, JUMP_FILLER5,

        CJUMP, CJMPC, CJPNC, CJMPZ,
        CJPNZ, CJMPE, CJPNE, CJMPG,
        CJPNG, CJMPL, CJPNL, CJUMP_FILLER1,
        CJUMP_FILLER2, CJUMP_FILLER3, CJUMP_FILLER4, CJUMP_FILLER5,

        NOFN_FILLER1, NOFN_FILLER2, NOFN_FILLER3, NOFN_FILLER4,
        NOFN_FILLER5, NOFN_FILLER6, NOFN_FILLER7, NOFN_FILLER8,
        NOFN_FILLER9, NOFN_FILLER10, NOFN_FILLER11, NOFN_FILLER12,
        NOFN_FILLER13, NOFN_FILLER14, NOFN_FILLER15, NOFN_FILLER16,

        KAOS
    }
}
